baseURL = "https://pgloader.io/"
languageCode = "en-us"
MetaDataFormat = "yaml"
title = "pgloader"

publishDir = "docs"

theme = "cocoa-eh"
builddrafts = true
canonifyurls = true
author = "Dimitri Fontaine"
disqusshortname = ""
pluralizelisttitles = false

[permalinks]
        blog = "blog/:slug/"

[params]
        dateform = "Jan 2, 2006"
        dateformfull = "Mon Jan 2 2006 15:04:05 MST"
        description = "Continuous Migration to PostgreSQL"
        copyright = "Copyright Â© 2017-2018 Dimitri Fontaine"
        # copyrightUrl = "https://creativecommons.org/licenses/by-sa/4.0/"
        logofile = "img/logo.png"
        faviconfile = "img/logo.png"
        highlightjs = true
        progressively = true
        share = true
        latestpostcount = 5
        github = "dimitri/pgloader"
        email = "dim@tapoueh.org"
        linkedin = "dimitrifontaine"
        twitter = "tapoueh"
        #facebook = "facebook_id"
        social_banner = "img/banner.png"
        usesmallsummarycard = true
        posts_navigation = true
        # issoHost = "comments.domain.tld:1234"
        # githubRepo = "githubUsername/repositoryName"
        small_banner_logo = false
        
[params.colors]
        identifier = "#527fc1f"
        identifier_dark = "#1a3152"
        trivial = "#6a7a8b"
        foreground = "#181d2a"
        background = "#f9f9f9"
        background_dark = "#282a36"
        code = "#87a5d2"
        type = "#97d28b"
        special = "#ffcb8d"
        value = "#96c2d7"
        statement = "#ff8e91"
